# Generated by Django 5.2 on 2025-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=80)),
                ('PHONE', models.CharField(max_length=50)),
                ('SUBJECT', models.CharField(max_length=50)),
            ],
        ),
    ]
