# Generated by Django 5.2 on 2025-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='EMAIL',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='NAME',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='PHONE',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='SUBJECT',
            field=models.CharField(max_length=30),
        ),
    ]
