# Generated by Django 5.2 on 2025-07-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0005_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='shopp',
        ),
    ]
